name: flutter_app_analytics_segment_provider
description: A new Segment provider for app analytics
version: 0.1.0
homepage:

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_app_analytics:
    git: https://github.com/uptech/flutter_app_analytics.git
  flutter_segment: ^3.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.3.2
  build_runner: ^2.3.3
